name: game-random-client Deploy dev

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: ['main']

jobs:
  deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        user: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            source ~/.bashrc
            node -v
            cd /home/minhduc/game-client-random
            git checkout .
            git checkout main
            git pull origin main
            npm install --legacy-peer-deps
            npm run buildDev

      - name: Send Discord notification on success
        uses: tsickert/discord-webhook@v6.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.WEBHOOKS_DISCORD }}
          content: "Your build was successful! Check it out"

      - name: Send Discord notification on failure
        uses: tsickert/discord-webhook@v6.0.0
        if: failure()
        with:
          webhook-url: ${{ secrets.WEBHOOKS_DISCORD }}
          content: "Your build failed. Please review the logs."

      # strategy:
      #   matrix:
      #     node-version: [20.x]

      # steps:
      #   - uses: actions/checkout@v3
      #   - name: Use Node.js ${{ matrix.node-version }}
      #     uses: actions/setup-node@v3
      #     with:
      #       node-version: ${{ matrix.node-version }}
      #       cache: 'npm'
      #   - run: npm install --legacy-peer-deps
      #   - run: npm run build --if-present
