name: game-random-client

on:
  push:
    branches: ['main']
  # pull_request:
  #   branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --legacy-peer-deps
      - run: npm run build --if-present

      - name: Send Discord notification on success
        uses: tsickert/discord-webhook@v6.0.0
        if: success()
        with:
          webhook-url: ${{ secrets.WEBHOOKS_DISCORD }}
          content: 'Your build was successful! Check it out'

      - name: Send Discord notification on failure
        uses: tsickert/discord-webhook@v6.0.0
        if: failure()
        with:
          webhook-url: ${{ secrets.WEBHOOKS_DISCORD }}
          content: 'Your build failed. Please review the logs.'
